version: 2
jobs:
  deploy: 
    docker:
      - image: circleci/node:10.19
    steps:
      - checkout 
      - run:
          name: npm install
          command: npm i
      - run:
          name: deploy to Firebase Hosting
          command: npm run deploy:ci

workflows:
  version: 2
  deploy: 
    jobs:
      - deploy:
          filters:
            branches:
              only: master